name = "jonsstore-ecommerce"
main = "src/index.js"
compatibility_date = "2024-01-15"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "jonsstore-db"
database_id = "your-database-id-here"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm run build"

# Routes (if using custom domain)
# routes = [
#   { pattern = "yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# KV Namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# R2 Buckets (if needed for file storage)
# [[r2_buckets]]
# binding = "ASSETS"
# bucket_name = "jonsstore-assets"
